package wd.d3.geom.segments {
    import __AS3__.vec.*;
    import flash.geom.*;

    public class SegmentColorGridSortableSubGeometry {

        private static var _id:int = 0;

        public var VERTEX_BUFFER_LENGTH:int = 11;
        private var v_offset:uint;
        private var _numVertices:uint;
        private var _numTriangles:uint;
        private var _numIndices:uint;
        public var _vertices:Vector.<Number>;
        public var _indices:Vector.<uint>;
        public var _uvs:Vector.<Number>;
        private var _lineCount:uint = 0;
        private var _thickness:Number;
        public var id:int;

        public function SegmentColorGridSortableSubGeometry(thickness:Number=1){
            this._vertices = new Vector.<Number>();
            this._indices = new Vector.<uint>();
            this._uvs = new Vector.<Number>();
            super();
            this._thickness = thickness;
            this.id = _id++;
        }
        public function get numVertices():uint{
            return (this._numVertices);
        }
        public function get numTriangles():uint{
            return (this._numTriangles);
        }
        public function mergeSegment(s:Vector3D, e:Vector3D, color:int, thickness:Number):void{
            var sr:Number = (((color >> 16) & 0xFF) / 0xFF);
            var sg:Number = (((color >> 8) & 0xFF) / 0xFF);
            var sb:Number = ((color & 0xFF) / 0xFF);
            var index:uint = this._vertices.length;
            var _temp1 = index;
            index = (index + 1);
            var _local9 = _temp1;
            this._vertices[_local9] = s.x;
            var _temp2 = index;
            index = (index + 1);
            var _local10 = _temp2;
            this._vertices[_local10] = s.y;
            var _temp3 = index;
            index = (index + 1);
            var _local11 = _temp3;
            this._vertices[_local11] = s.z;
            var _temp4 = index;
            index = (index + 1);
            var _local12 = _temp4;
            this._vertices[_local12] = e.x;
            var _temp5 = index;
            index = (index + 1);
            var _local13 = _temp5;
            this._vertices[_local13] = e.y;
            var _temp6 = index;
            index = (index + 1);
            var _local14 = _temp6;
            this._vertices[_local14] = e.z;
            var _temp7 = index;
            index = (index + 1);
            var _local15 = _temp7;
            this._vertices[_local15] = thickness;
            var _temp8 = index;
            index = (index + 1);
            var _local16 = _temp8;
            this._vertices[_local16] = sr;
            var _temp9 = index;
            index = (index + 1);
            var _local17 = _temp9;
            this._vertices[_local17] = sg;
            var _temp10 = index;
            index = (index + 1);
            var _local18 = _temp10;
            this._vertices[_local18] = sb;
            var _temp11 = index;
            index = (index + 1);
            var _local19 = _temp11;
            this._vertices[_local19] = 1;
            var _temp12 = index;
            index = (index + 1);
            var _local20 = _temp12;
            this._vertices[_local20] = e.x;
            var _temp13 = index;
            index = (index + 1);
            var _local21 = _temp13;
            this._vertices[_local21] = e.y;
            var _temp14 = index;
            index = (index + 1);
            var _local22 = _temp14;
            this._vertices[_local22] = e.z;
            var _temp15 = index;
            index = (index + 1);
            var _local23 = _temp15;
            this._vertices[_local23] = s.x;
            var _temp16 = index;
            index = (index + 1);
            var _local24 = _temp16;
            this._vertices[_local24] = s.y;
            var _temp17 = index;
            index = (index + 1);
            var _local25 = _temp17;
            this._vertices[_local25] = s.z;
            var _temp18 = index;
            index = (index + 1);
            var _local26 = _temp18;
            this._vertices[_local26] = -(thickness);
            var _temp19 = index;
            index = (index + 1);
            var _local27 = _temp19;
            this._vertices[_local27] = sr;
            var _temp20 = index;
            index = (index + 1);
            var _local28 = _temp20;
            this._vertices[_local28] = sg;
            var _temp21 = index;
            index = (index + 1);
            var _local29 = _temp21;
            this._vertices[_local29] = sb;
            var _temp22 = index;
            index = (index + 1);
            var _local30 = _temp22;
            this._vertices[_local30] = 1;
            var _temp23 = index;
            index = (index + 1);
            var _local31 = _temp23;
            this._vertices[_local31] = s.x;
            var _temp24 = index;
            index = (index + 1);
            var _local32 = _temp24;
            this._vertices[_local32] = s.y;
            var _temp25 = index;
            index = (index + 1);
            var _local33 = _temp25;
            this._vertices[_local33] = s.z;
            var _temp26 = index;
            index = (index + 1);
            var _local34 = _temp26;
            this._vertices[_local34] = e.x;
            var _temp27 = index;
            index = (index + 1);
            var _local35 = _temp27;
            this._vertices[_local35] = e.y;
            var _temp28 = index;
            index = (index + 1);
            var _local36 = _temp28;
            this._vertices[_local36] = e.z;
            var _temp29 = index;
            index = (index + 1);
            var _local37 = _temp29;
            this._vertices[_local37] = -(thickness);
            var _temp30 = index;
            index = (index + 1);
            var _local38 = _temp30;
            this._vertices[_local38] = sr;
            var _temp31 = index;
            index = (index + 1);
            var _local39 = _temp31;
            this._vertices[_local39] = sg;
            var _temp32 = index;
            index = (index + 1);
            var _local40 = _temp32;
            this._vertices[_local40] = sb;
            var _temp33 = index;
            index = (index + 1);
            var _local41 = _temp33;
            this._vertices[_local41] = 1;
            var _temp34 = index;
            index = (index + 1);
            var _local42 = _temp34;
            this._vertices[_local42] = e.x;
            var _temp35 = index;
            index = (index + 1);
            var _local43 = _temp35;
            this._vertices[_local43] = e.y;
            var _temp36 = index;
            index = (index + 1);
            var _local44 = _temp36;
            this._vertices[_local44] = e.z;
            var _temp37 = index;
            index = (index + 1);
            var _local45 = _temp37;
            this._vertices[_local45] = s.x;
            var _temp38 = index;
            index = (index + 1);
            var _local46 = _temp38;
            this._vertices[_local46] = s.y;
            var _temp39 = index;
            index = (index + 1);
            var _local47 = _temp39;
            this._vertices[_local47] = s.z;
            var _temp40 = index;
            index = (index + 1);
            var _local48 = _temp40;
            this._vertices[_local48] = thickness;
            var _temp41 = index;
            index = (index + 1);
            var _local49 = _temp41;
            this._vertices[_local49] = sr;
            var _temp42 = index;
            index = (index + 1);
            var _local50 = _temp42;
            this._vertices[_local50] = sg;
            var _temp43 = index;
            index = (index + 1);
            var _local51 = _temp43;
            this._vertices[_local51] = sb;
            var _temp44 = index;
            index = (index + 1);
            var _local52 = _temp44;
            this._vertices[_local52] = 1;
            index = (this._lineCount << 2);
            this._indices.push(index, (index + 1), (index + 2), (index + 3), (index + 2), (index + 1));
            this._numVertices = (this._vertices.length / this.VERTEX_BUFFER_LENGTH);
            this._numIndices = this._indices.length;
            this._numTriangles = (this._indices.length / 3);
            this._lineCount++;
        }
        public function dispose():void{
            this._vertices.length = 0;
            this._vertices = null;
            this._indices.length = 0;
            this._indices = null;
            this._uvs.length = 0;
            this._uvs = null;
        }

    }
}//package wd.d3.geom.segments 
